// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { SATCAT, SATCATT } from './SATCAT';


export class SATCATCOLLECTION {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SATCATCOLLECTION {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSATCATCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:SATCATCOLLECTION):SATCATCOLLECTION {
  return (obj || new SATCATCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSATCATCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:SATCATCOLLECTION):SATCATCOLLECTION {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SATCATCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:SATCAT):SATCAT|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SATCAT()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

RECORDSLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSATCATCOLLECTION(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRECORDS(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRECORDSVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRECORDSVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSATCATCOLLECTION(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSATCATCOLLECTION(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  SATCATCOLLECTION.startSATCATCOLLECTION(builder);
  SATCATCOLLECTION.addRECORDS(builder, RECORDSOffset);
  return SATCATCOLLECTION.endSATCATCOLLECTION(builder);
}

unpack(): SATCATCOLLECTIONT {
  return new SATCATCOLLECTIONT(
    this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength())
  );
}


unpackTo(_o: SATCATCOLLECTIONT): void {
  _o.RECORDS = this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength());
}
}

export class SATCATCOLLECTIONT {
constructor(
  public RECORDS: (SATCATT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = SATCATCOLLECTION.createRECORDSVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return SATCATCOLLECTION.createSATCATCOLLECTION(builder,
    RECORDS
  );
}
}
