// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { OEM, OEMT } from './OEM';


export class OEMCOLLECTION {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):OEMCOLLECTION {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOEMCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:OEMCOLLECTION):OEMCOLLECTION {
  return (obj || new OEMCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOEMCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:OEMCOLLECTION):OEMCOLLECTION {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OEMCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:OEM):OEM|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new OEM()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

RECORDSLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startOEMCOLLECTION(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRECORDS(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRECORDSVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRECORDSVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endOEMCOLLECTION(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOEMCOLLECTION(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  OEMCOLLECTION.startOEMCOLLECTION(builder);
  OEMCOLLECTION.addRECORDS(builder, RECORDSOffset);
  return OEMCOLLECTION.endOEMCOLLECTION(builder);
}

unpack(): OEMCOLLECTIONT {
  return new OEMCOLLECTIONT(
    this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength())
  );
}


unpackTo(_o: OEMCOLLECTIONT): void {
  _o.RECORDS = this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength());
}
}

export class OEMCOLLECTIONT {
constructor(
  public RECORDS: (OEMT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = OEMCOLLECTION.createRECORDSVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return OEMCOLLECTION.createOEMCOLLECTION(builder,
    RECORDS
  );
}
}
