// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { MPE, MPET } from './MPE';


export class MPECOLLECTION {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):MPECOLLECTION {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMPECOLLECTION(bb:flatbuffers.ByteBuffer, obj?:MPECOLLECTION):MPECOLLECTION {
  return (obj || new MPECOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMPECOLLECTION(bb:flatbuffers.ByteBuffer, obj?:MPECOLLECTION):MPECOLLECTION {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MPECOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:MPE):MPE|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MPE()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

RECORDSLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMPECOLLECTION(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRECORDS(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRECORDSVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRECORDSVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMPECOLLECTION(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMPECOLLECTION(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  MPECOLLECTION.startMPECOLLECTION(builder);
  MPECOLLECTION.addRECORDS(builder, RECORDSOffset);
  return MPECOLLECTION.endMPECOLLECTION(builder);
}

unpack(): MPECOLLECTIONT {
  return new MPECOLLECTIONT(
    this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength())
  );
}


unpackTo(_o: MPECOLLECTIONT): void {
  _o.RECORDS = this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength());
}
}

export class MPECOLLECTIONT {
constructor(
  public RECORDS: (MPET)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = MPECOLLECTION.createRECORDSVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return MPECOLLECTION.createMPECOLLECTION(builder,
    RECORDS
  );
}
}
