// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DPM, DPMT } from './DPM.js';


export class DPMCOLLECTION implements flatbuffers.IUnpackableObject<DPMCOLLECTIONT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DPMCOLLECTION {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDPMCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:DPMCOLLECTION):DPMCOLLECTION {
  return (obj || new DPMCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDPMCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:DPMCOLLECTION):DPMCOLLECTION {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DPMCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:DPM):DPM|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DPM()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

recordsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDPMCOLLECTION(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRecords(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRecordsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRecordsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDPMCOLLECTION(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDPMCOLLECTION(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  DPMCOLLECTION.startDPMCOLLECTION(builder);
  DPMCOLLECTION.addRecords(builder, RECORDSOffset);
  return DPMCOLLECTION.endDPMCOLLECTION(builder);
}

unpack(): DPMCOLLECTIONT {
  return new DPMCOLLECTIONT(
    this.bb!.createObjList<DPM, DPMT>(this.RECORDS.bind(this), this.recordsLength())
  );
}


unpackTo(_o: DPMCOLLECTIONT): void {
  _o.RECORDS = this.bb!.createObjList<DPM, DPMT>(this.RECORDS.bind(this), this.recordsLength());
}
}

export class DPMCOLLECTIONT implements flatbuffers.IGeneratedObject {
constructor(
  public RECORDS: (DPMT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = DPMCOLLECTION.createRecordsVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return DPMCOLLECTION.createDPMCOLLECTION(builder,
    RECORDS
  );
}
}
