// automatically generated by the FlatBuffers compiler, do not modify

export { CONTACT_POINT, CONTACT_POINTT } from './CONTACT_POINT.js';
export { DPM, DPMT } from './DPM.js';
export { DPMCOLLECTION, DPMCOLLECTIONT } from './DPMCOLLECTION.js';
export { PERSON, PERSONT } from './PERSON.js';
export { POSTAL_ADDRESS, POSTAL_ADDRESST } from './POSTAL_ADDRESS.js';
