// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class POSTAL_ADDRESS implements flatbuffers.IUnpackableObject<POSTAL_ADDRESST> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):POSTAL_ADDRESS {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPOSTAL_ADDRESS(bb:flatbuffers.ByteBuffer, obj?:POSTAL_ADDRESS):POSTAL_ADDRESS {
  return (obj || new POSTAL_ADDRESS()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPOSTAL_ADDRESS(bb:flatbuffers.ByteBuffer, obj?:POSTAL_ADDRESS):POSTAL_ADDRESS {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new POSTAL_ADDRESS()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

GUID():string|null
GUID(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
GUID(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ADDRESS_COUNTRY():string|null
ADDRESS_COUNTRY(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ADDRESS_COUNTRY(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ADDRESS_REGION():string|null
ADDRESS_REGION(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ADDRESS_REGION(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ADDRESS_LOCALITY():string|null
ADDRESS_LOCALITY(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ADDRESS_LOCALITY(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

POSTAL_CODE():string|null
POSTAL_CODE(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
POSTAL_CODE(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

STREET_ADDRESS():string|null
STREET_ADDRESS(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
STREET_ADDRESS(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPOSTAL_ADDRESS(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addGuid(builder:flatbuffers.Builder, GUIDOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, GUIDOffset, 0);
}

static addAddressCountry(builder:flatbuffers.Builder, ADDRESS_COUNTRYOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, ADDRESS_COUNTRYOffset, 0);
}

static addAddressRegion(builder:flatbuffers.Builder, ADDRESS_REGIONOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, ADDRESS_REGIONOffset, 0);
}

static addAddressLocality(builder:flatbuffers.Builder, ADDRESS_LOCALITYOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, ADDRESS_LOCALITYOffset, 0);
}

static addPostalCode(builder:flatbuffers.Builder, POSTAL_CODEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, POSTAL_CODEOffset, 0);
}

static addStreetAddress(builder:flatbuffers.Builder, STREET_ADDRESSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, STREET_ADDRESSOffset, 0);
}

static endPOSTAL_ADDRESS(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPOSTAL_ADDRESS(builder:flatbuffers.Builder, GUIDOffset:flatbuffers.Offset, ADDRESS_COUNTRYOffset:flatbuffers.Offset, ADDRESS_REGIONOffset:flatbuffers.Offset, ADDRESS_LOCALITYOffset:flatbuffers.Offset, POSTAL_CODEOffset:flatbuffers.Offset, STREET_ADDRESSOffset:flatbuffers.Offset):flatbuffers.Offset {
  POSTAL_ADDRESS.startPOSTAL_ADDRESS(builder);
  POSTAL_ADDRESS.addGuid(builder, GUIDOffset);
  POSTAL_ADDRESS.addAddressCountry(builder, ADDRESS_COUNTRYOffset);
  POSTAL_ADDRESS.addAddressRegion(builder, ADDRESS_REGIONOffset);
  POSTAL_ADDRESS.addAddressLocality(builder, ADDRESS_LOCALITYOffset);
  POSTAL_ADDRESS.addPostalCode(builder, POSTAL_CODEOffset);
  POSTAL_ADDRESS.addStreetAddress(builder, STREET_ADDRESSOffset);
  return POSTAL_ADDRESS.endPOSTAL_ADDRESS(builder);
}

unpack(): POSTAL_ADDRESST {
  return new POSTAL_ADDRESST(
    this.GUID(),
    this.ADDRESS_COUNTRY(),
    this.ADDRESS_REGION(),
    this.ADDRESS_LOCALITY(),
    this.POSTAL_CODE(),
    this.STREET_ADDRESS()
  );
}


unpackTo(_o: POSTAL_ADDRESST): void {
  _o.GUID = this.GUID();
  _o.ADDRESS_COUNTRY = this.ADDRESS_COUNTRY();
  _o.ADDRESS_REGION = this.ADDRESS_REGION();
  _o.ADDRESS_LOCALITY = this.ADDRESS_LOCALITY();
  _o.POSTAL_CODE = this.POSTAL_CODE();
  _o.STREET_ADDRESS = this.STREET_ADDRESS();
}
}

export class POSTAL_ADDRESST implements flatbuffers.IGeneratedObject {
constructor(
  public GUID: string|Uint8Array|null = null,
  public ADDRESS_COUNTRY: string|Uint8Array|null = null,
  public ADDRESS_REGION: string|Uint8Array|null = null,
  public ADDRESS_LOCALITY: string|Uint8Array|null = null,
  public POSTAL_CODE: string|Uint8Array|null = null,
  public STREET_ADDRESS: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const GUID = (this.GUID !== null ? builder.createString(this.GUID!) : 0);
  const ADDRESS_COUNTRY = (this.ADDRESS_COUNTRY !== null ? builder.createString(this.ADDRESS_COUNTRY!) : 0);
  const ADDRESS_REGION = (this.ADDRESS_REGION !== null ? builder.createString(this.ADDRESS_REGION!) : 0);
  const ADDRESS_LOCALITY = (this.ADDRESS_LOCALITY !== null ? builder.createString(this.ADDRESS_LOCALITY!) : 0);
  const POSTAL_CODE = (this.POSTAL_CODE !== null ? builder.createString(this.POSTAL_CODE!) : 0);
  const STREET_ADDRESS = (this.STREET_ADDRESS !== null ? builder.createString(this.STREET_ADDRESS!) : 0);

  return POSTAL_ADDRESS.createPOSTAL_ADDRESS(builder,
    GUID,
    ADDRESS_COUNTRY,
    ADDRESS_REGION,
    ADDRESS_LOCALITY,
    POSTAL_CODE,
    STREET_ADDRESS
  );
}
}
